services:
  glance:
    container_name: glance
    image: glanceapp/glance
    environment:
      - TZ:Asia/Calcutta
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./assets:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8085:8080
    env_file: .env
